### ISSUE TITLE
Badger 2040 w and RTC

### ISSUE THREAD

**Issue by stayfrosty00** [pimoroni/pimoroni-pico#710] opened 2023-03-10 00:30 UTC
The documentation says there is a way to wake the Badger using the RTC but it does not seem to be implemented in badger2040w.py like it is with the inky frame.

**Comment by Gadgetoid** [comment] 2023-03-10 12:50
Dupe of https://github.com/pimoroni/badger2040/issues/4

I'm working on porting the basic RTC management functions I wrote for Inky Frame.

**Closed by Gadgetoid** 2023-03-10 12:50 UTC

**Comment by stayfrosty00** [comment] 2023-03-10 15:09
Thank you for your hard work!
